<a href="https://colab.research.google.com/github/24f1000525/ML/blob/main/Intro_to_Panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
pd.__version__

'2.2.2'

The Primary data Structire in pandas are implemented as two classes:

**DataFrame**- which can
be imagine as relational data table with rows and columns.

**Series**- Which is single column .each row can be labeled via index.

In [ ]:
from sklearn.datasets import load_diabetes

diabetes=load_diabetes(as_frame=True)
print(type(diabetes['data']))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
df=diabetes['data']
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

## Creating pandas dataframe from series

In [ ]:
cities=pd.Series(['Mumbai','Bangalore','Chennai','Delhi'])
population=pd.Series([170000,130000,60000])

city_info_df=pd.DataFrame({'City':cities,'Population':population})
city_info_df

        City  Population
0     Mumbai    170000.0
1  Bangalore    130000.0
2    Chennai     60000.0
3      Delhi         NaN

#Exploring data in Dataframe

quickly examine a few entries in datframe. say first 5 and last 5

In [ ]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

Find out number of rows and columns in the dataframes

In [ ]:
df.shape

(442, 10)

Lets see the names of the columns

In [ ]:
df.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

Lets get summary of dataset

In [ ]:
df.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

In [ ]:
df.describe(percentiles=[0.2,0.6,0.8])

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
20%,-4.547248e-02,-4.464164e-02,-4.048038e-02,-4.009893e-02,-3.871969e-02,-3.695017e-02,-3.971921e-02,-3.949338e-02,-4.117617e-02,-3.835666e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
60%,1.628068e-02,5.068012e-02,5.218854e-03,8.100982e-03,8.062710e-03,8.706873e-03,8.142084e-03,-2.592262e-03,1.255119e-02,7.206516e-03
80%,4.170844e-02,5.068012e-02,4.229559e-02,4.941519e-02,3.943444e-02,3.952068e-02,3.759519e-02,3.430886e-02,3.885335e-02,3.620126e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,442.0,-2.511817e-19,0.047619,-0.107226,-0.037299,0.005383,0.038076,0.110727
sex,442.0,1.230790e-17,0.047619,-0.044642,-0.044642,-0.044642,0.050680,0.050680
bmi,442.0,-2.245564e-16,0.047619,-0.090275,-0.034229,-0.007284,0.031248,0.170555
bp,442.0,-4.797570e-17,0.047619,-0.112399,-0.036656,-0.005670,0.035644,0.132044
s1,442.0,-1.381499e-17,0.047619,-0.126781,-0.034248,-0.004321,0.028358,0.153914
s2,442.0,3.918434e-17,0.047619,-0.115613,-0.030358,-0.003819,0.029844,0.198788
s3,442.0,-5.777179e-18,0.047619,-0.102307,-0.035117,-0.006584,0.029312,0.181179
s4,442.0,-9.042540e-18,0.047619,-0.076395,-0.039493,-0.002592,0.034309,0.185234
s5,442.0,9.293722e-17,0.047619,-0.126097,-0.033246,-0.001947,0.032432,0.133597
s6,442.0,1.130318e-17,0.047619,-0.137767,-0.033179,-0.001078,0.027917,0.135612

## Selection

In [ ]:
df['age']

0      0.038076
1     -0.001882
2      0.085299
3     -0.089063
4      0.005383
         ...
437    0.041708
438   -0.005515
439    0.041708
440   -0.045472
441   -0.045472
Name: age, Length: 442, dtype: float64

In [ ]:
type(df['age'])

pandas.core.series.Series

In [ ]:
df['age'][0]

np.float64(0.038075906433423026)

In [ ]:
df['age'][:5]

0    0.038076
1   -0.001882
2    0.085299
3   -0.089063
4    0.005383
Name: age, dtype: float64

In [ ]:
df['age'][-5:]

437    0.041708
438   -0.005515
439    0.041708
440   -0.045472
441   -0.045472
Name: age, dtype: float64

In [ ]:
df[['age','sex']]

          age       sex
0    0.038076  0.050680
1   -0.001882 -0.044642
2    0.085299  0.050680
3   -0.089063 -0.044642
4    0.005383 -0.044642
..        ...       ...
437  0.041708  0.050680
438 -0.005515  0.050680
439  0.041708  0.050680
440 -0.045472 -0.044642
441 -0.045472 -0.044642

[442 rows x 2 columns]

* ```.loc```  indices value
* ```.iloc``` integer value

In [ ]:
df.iloc[0] #df[0] not works

age    0.038076
sex    0.050680
bmi    0.061696
bp     0.021872
s1    -0.044223
s2    -0.034821
s3    -0.043401
s4    -0.002592
s5     0.019907
s6    -0.017646
Name: 0, dtype: float64

In [ ]:
df.loc[0]

age    0.038076
sex    0.050680
bmi    0.061696
bp     0.021872
s1    -0.044223
s2    -0.034821
s3    -0.043401
s4    -0.002592
s5     0.019907
s6    -0.017646
Name: 0, dtype: float64

In [ ]:
df.loc[4,'age'] #but not df.iloc[4,'age']

np.float64(0.005383060374248237)

In [ ]:
df.iloc[4,0:2]

age    0.005383
sex   -0.044642
Name: 4, dtype: float64

In [ ]:
df.loc[4,['age','sex']]

age    0.005383
sex   -0.044642
Name: 4, dtype: float64

In [ ]:
df.loc[df.age<0.005383]

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504
...,...,...,...,...,...,...,...,...,...,...
435,-0.012780,-0.044642,-0.023451,-0.040099,-0.016704,0.004636,-0.017629,-0.002592,-0.038460,-0.038357
436,-0.056370,-0.044642,-0.074108,-0.050427,-0.024960,-0.047034,0.092820,-0.076395,-0.061176,-0.046641
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [ ]:
import numpy as np

In [ ]:
df=pd.DataFrame(np.random.rand(9,4),index=list('abcdefghi'),columns=list("ABCD"))

In [ ]:
df.shape

(9, 4)

In [ ]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, a to i
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       9 non-null      float64
 1   B       9 non-null      float64
 2   C       9 non-null      float64
 3   D       9 non-null      float64
dtypes: float64(4)
memory usage: 360.0+ bytes

In [ ]:
df.head()

          A         B         C         D
a  0.044621  0.806835  0.409859  0.868048
b  0.807353  0.268252  0.047439  0.734871
c  0.185756  0.818254  0.685567  0.783202
d  0.749321  0.375725  0.965312  0.806235
e  0.254259  0.084998  0.442916  0.961164

In [ ]:
another_df=pd.DataFrame(
    np.random.rand(100,4),
    index=range(10,110),
    columns=list("ABCD")
)

In [ ]:
another_df.head()

           A         B         C         D
10  0.438875  0.219726  0.096211  0.159472
11  0.118803  0.785305  0.873286  0.623090
12  0.902133  0.152921  0.355811  0.429705
13  0.979085  0.766421  0.420990  0.863945
14  0.271717  0.228487  0.765716  0.319476

In [ ]:
df.loc['a']

A    0.044621
B    0.806835
C    0.409859
D    0.868048
Name: a, dtype: float64

In [ ]:
df.iloc[0:4,0:3]

          A         B         C
a  0.044621  0.806835  0.409859
b  0.807353  0.268252  0.047439
c  0.185756  0.818254  0.685567
d  0.749321  0.375725  0.965312

In [ ]:
selector=lambda df: df['A']>0.5

In [ ]:
selector

In [ ]:
df.loc[selector]

          A         B         C         D
b  0.807353  0.268252  0.047439  0.734871
d  0.749321  0.375725  0.965312  0.806235
f  0.948944  0.232702  0.994588  0.517221
i  0.685136  0.585681  0.539696  0.150015

In [ ]:
selector =lambda df:(df['A']>0.5) &(df['B']<0.2)

In [ ]:
df.loc[selector]

Empty DataFrame
Columns: [A, B, C, D]
Index: []

## Adding a column in the dataframe

In [ ]:
df['E']=df['A']*100

In [ ]:
df

          A         B         C         D          E
a  0.044621  0.806835  0.409859  0.868048   4.462073
b  0.807353  0.268252  0.047439  0.734871  80.735342
c  0.185756  0.818254  0.685567  0.783202  18.575618
d  0.749321  0.375725  0.965312  0.806235  74.932104
e  0.254259  0.084998  0.442916  0.961164  25.425936
f  0.948944  0.232702  0.994588  0.517221  94.894450
g  0.091066  0.168082  0.829915  0.808943   9.106608
h  0.296238  0.636957  0.723925  0.254685  29.623774
i  0.685136  0.585681  0.539696  0.150015  68.513604

In [ ]:
criteria=df['A']<0.2

In [ ]:
criteria

a     True
b    False
c     True
d    False
e    False
f    False
g     True
h    False
i    False
Name: A, dtype: bool

In [ ]:
df.loc[criteria,'A']=0
df

          A         B         C         D          E
a  0.000000  0.806835  0.409859  0.868048   4.462073
b  0.807353  0.268252  0.047439  0.734871  80.735342
c  0.000000  0.818254  0.685567  0.783202  18.575618
d  0.749321  0.375725  0.965312  0.806235  74.932104
e  0.254259  0.084998  0.442916  0.961164  25.425936
f  0.948944  0.232702  0.994588  0.517221  94.894450
g  0.000000  0.168082  0.829915  0.808943   9.106608
h  0.296238  0.636957  0.723925  0.254685  29.623774
i  0.685136  0.585681  0.539696  0.150015  68.513604

In [ ]:
cities=["mumbai",'kolkata','delhi','chennia','bengalure','pune','hyderabad','indore','varanasi']

In [ ]:
df['city']=cities

In [ ]:
df

          A         B         C         D          E       city
a  0.000000  0.806835  0.409859  0.868048   4.462073     mumbai
b  0.807353  0.268252  0.047439  0.734871  80.735342    kolkata
c  0.000000  0.818254  0.685567  0.783202  18.575618      delhi
d  0.749321  0.375725  0.965312  0.806235  74.932104    chennia
e  0.254259  0.084998  0.442916  0.961164  25.425936  bengalure
f  0.948944  0.232702  0.994588  0.517221  94.894450       pune
g  0.000000  0.168082  0.829915  0.808943   9.106608  hyderabad
h  0.296238  0.636957  0.723925  0.254685  29.623774     indore
i  0.685136  0.585681  0.539696  0.150015  68.513604   varanasi

In [ ]:
df_copy=df.copy()

In [ ]:
criteria=df_copy['city'].isin(['pune','delhii'])

In [ ]:
criteria

a    False
b    False
c    False
d    False
e    False
f     True
g    False
h    False
i    False
Name: city, dtype: bool

In [ ]:
df_copy.loc[df.city=='delhi','city']='delhii'

In [ ]:
df_copy

          A         B         C         D          E       city
a  0.000000  0.806835  0.409859  0.868048   4.462073     mumbai
b  0.807353  0.268252  0.047439  0.734871  80.735342    kolkata
c  0.000000  0.818254  0.685567  0.783202  18.575618     delhii
d  0.749321  0.375725  0.965312  0.806235  74.932104    chennia
e  0.254259  0.084998  0.442916  0.961164  25.425936  bengalure
f  0.948944  0.232702  0.994588  0.517221  94.894450       pune
g  0.000000  0.168082  0.829915  0.808943   9.106608  hyderabad
h  0.296238  0.636957  0.723925  0.254685  29.623774     indore
i  0.685136  0.585681  0.539696  0.150015  68.513604   varanasi

In [ ]:
df_copy[criteria]

          A         B         C         D         E  city
f  0.948944  0.232702  0.994588  0.517221  94.89445  pune

In [ ]:
df_copy.loc[df_copy.city=='delho',['city','new_cities']]='delhi'

In [ ]:
df_copy

          A         B         C         D          E       city new_cities
a  0.000000  0.806835  0.409859  0.868048   4.462073     mumbai        NaN
b  0.807353  0.268252  0.047439  0.734871  80.735342    kolkata        NaN
c  0.000000  0.818254  0.685567  0.783202  18.575618     delhii        NaN
d  0.749321  0.375725  0.965312  0.806235  74.932104    chennia        NaN
e  0.254259  0.084998  0.442916  0.961164  25.425936  bengalure        NaN
f  0.948944  0.232702  0.994588  0.517221  94.894450       pune        NaN
g  0.000000  0.168082  0.829915  0.808943   9.106608  hyderabad        NaN
h  0.296238  0.636957  0.723925  0.254685  29.623774     indore        NaN
i  0.685136  0.585681  0.539696  0.150015  68.513604   varanasi        NaN

In [ ]:
df_copy.drop(['new_cities'],axis=1)

          A         B         C         D          E       city
a  0.000000  0.806835  0.409859  0.868048   4.462073     mumbai
b  0.807353  0.268252  0.047439  0.734871  80.735342    kolkata
c  0.000000  0.818254  0.685567  0.783202  18.575618     delhii
d  0.749321  0.375725  0.965312  0.806235  74.932104    chennia
e  0.254259  0.084998  0.442916  0.961164  25.425936  bengalure
f  0.948944  0.232702  0.994588  0.517221  94.894450       pune
g  0.000000  0.168082  0.829915  0.808943   9.106608  hyderabad
h  0.296238  0.636957  0.723925  0.254685  29.623774     indore
i  0.685136  0.585681  0.539696  0.150015  68.513604   varanasi

In [ ]:
df_copy.sample(3)

          A         B         C         D          E      city new_cities
f  0.948944  0.232702  0.994588  0.517221  94.894450      pune        NaN
i  0.685136  0.585681  0.539696  0.150015  68.513604  varanasi        NaN
h  0.296238  0.636957  0.723925  0.254685  29.623774    indore        NaN

In [ ]:
df_copy.sample(3,random_state=42)

          A         B         C         D          E     city new_cities
h  0.296238  0.636957  0.723925  0.254685  29.623774   indore        NaN
b  0.807353  0.268252  0.047439  0.734871  80.735342  kolkata        NaN
f  0.948944  0.232702  0.994588  0.517221  94.894450     pune        NaN

In [ ]:
df_copy.sample(3,replace=True)

          A         B         C         D          E       city new_cities
d  0.749321  0.375725  0.965312  0.806235  74.932104    chennia        NaN
g  0.000000  0.168082  0.829915  0.808943   9.106608  hyderabad        NaN
f  0.948944  0.232702  0.994588  0.517221  94.894450       pune        NaN

## Aggregation and Grouping

In [ ]:
random_state=np.random.RandomState(42 )
random_series=pd.Series(random_state.rand(10))
random_series

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
5    0.155995
6    0.058084
7    0.866176
8    0.601115
9    0.708073
dtype: float64

In [ ]:
random_series.mean()

np.float64(0.5201367359526748)

In [ ]:
random_series.std()

0.3158656227180549

Lets create a dataframe with 5 rows and 2 column

In [ ]:
df=pd.DataFrame({'A':random_state.rand(5),'B':random_state.rand(5)})
df

          A         B
0  0.607545  0.808397
1  0.170524  0.304614
2  0.065052  0.097672
3  0.948886  0.684233
4  0.965632  0.440152

In [ ]:
df.sum()

A    2.757638
B    2.335069
dtype: float64

Try this operation row wise

In [ ]:
df.mean(axis=1)

0    0.707971
1    0.237569
2    0.081362
3    0.816559
4    0.702892
dtype: float64

groupy
three stages

split-we split dataframe into multiple smaller dataframe based on the values of keys
Apply-we apply desired aggregation on each dataframe.
combine-we combine result from apply state into dataframe

In [ ]:
df=pd.DataFrame({"key":["A","B","C","A","B","C"],"data":[1,2,3,4,5,6]})

In [ ]:
df

  key  data
0   A     1
1   B     2
2   C     3
3   A     4
4   B     5
5   C     6

In [ ]:
df.groupby('key').sum()

     data
key
A       5
B       7
C       9