<a href="https://colab.research.google.com/github/24f1000525/ML/blob/main/Intro_to_Panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.__version__

'2.2.2'

The Primary data Structire in pandas are implemented as two classes:

**DataFrame**- which can
be imagine as relational data table with rows and columns.

**Series**- Which is single column .each row can be labeled via index.

In [2]:
from sklearn.datasets import load_diabetes

diabetes=load_diabetes(as_frame=True)
print(type(diabetes['data']))

<class 'pandas.core.frame.DataFrame'>

In [3]:
df=diabetes['data']
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641
...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

## Creating pandas dataframe from series

In [4]:
cities=pd.Series(['Mumbai','Bangalore','Chennai','Delhi'])
population=pd.Series([170000,130000,60000])

city_info_df=pd.DataFrame({'City':cities,'Population':population})
city_info_df

        City  Population
0     Mumbai    170000.0
1  Bangalore    130000.0
2    Chennai     60000.0
3      Delhi         NaN

#Exploring data in Dataframe

quickly examine a few entries in datframe. say first 5 and last 5

In [5]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

Find out number of rows and columns in the dataframes

In [6]:
df.shape

(442, 10)

Lets see the names of the columns

In [7]:
df.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
dtypes: float64(10)
memory usage: 34.7 KB

Lets get summary of dataset

In [9]:
df.describe()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
25%,-3.729927e-02,-4.464164e-02,-3.422907e-02,-3.665608e-02,-3.424784e-02,-3.035840e-02,-3.511716e-02,-3.949338e-02,-3.324559e-02,-3.317903e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
75%,3.807591e-02,5.068012e-02,3.124802e-02,3.564379e-02,2.835801e-02,2.984439e-02,2.931150e-02,3.430886e-02,3.243232e-02,2.791705e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

In [10]:
df.describe(percentiles=[0.2,0.6,0.8])

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
count,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02,4.420000e+02
mean,-2.511817e-19,1.230790e-17,-2.245564e-16,-4.797570e-17,-1.381499e-17,3.918434e-17,-5.777179e-18,-9.042540e-18,9.293722e-17,1.130318e-17
std,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02,4.761905e-02
min,-1.072256e-01,-4.464164e-02,-9.027530e-02,-1.123988e-01,-1.267807e-01,-1.156131e-01,-1.023071e-01,-7.639450e-02,-1.260971e-01,-1.377672e-01
20%,-4.547248e-02,-4.464164e-02,-4.048038e-02,-4.009893e-02,-3.871969e-02,-3.695017e-02,-3.971921e-02,-3.949338e-02,-4.117617e-02,-3.835666e-02
50%,5.383060e-03,-4.464164e-02,-7.283766e-03,-5.670422e-03,-4.320866e-03,-3.819065e-03,-6.584468e-03,-2.592262e-03,-1.947171e-03,-1.077698e-03
60%,1.628068e-02,5.068012e-02,5.218854e-03,8.100982e-03,8.062710e-03,8.706873e-03,8.142084e-03,-2.592262e-03,1.255119e-02,7.206516e-03
80%,4.170844e-02,5.068012e-02,4.229559e-02,4.941519e-02,3.943444e-02,3.952068e-02,3.759519e-02,3.430886e-02,3.885335e-02,3.620126e-02
max,1.107267e-01,5.068012e-02,1.705552e-01,1.320436e-01,1.539137e-01,1.987880e-01,1.811791e-01,1.852344e-01,1.335973e-01,1.356118e-01

In [11]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,442.0,-2.511817e-19,0.047619,-0.107226,-0.037299,0.005383,0.038076,0.110727
sex,442.0,1.230790e-17,0.047619,-0.044642,-0.044642,-0.044642,0.050680,0.050680
bmi,442.0,-2.245564e-16,0.047619,-0.090275,-0.034229,-0.007284,0.031248,0.170555
bp,442.0,-4.797570e-17,0.047619,-0.112399,-0.036656,-0.005670,0.035644,0.132044
s1,442.0,-1.381499e-17,0.047619,-0.126781,-0.034248,-0.004321,0.028358,0.153914
s2,442.0,3.918434e-17,0.047619,-0.115613,-0.030358,-0.003819,0.029844,0.198788
s3,442.0,-5.777179e-18,0.047619,-0.102307,-0.035117,-0.006584,0.029312,0.181179
s4,442.0,-9.042540e-18,0.047619,-0.076395,-0.039493,-0.002592,0.034309,0.185234
s5,442.0,9.293722e-17,0.047619,-0.126097,-0.033246,-0.001947,0.032432,0.133597
s6,442.0,1.130318e-17,0.047619,-0.137767,-0.033179,-0.001078,0.027917,0.135612

## Selection

In [12]:
df['age']

0      0.038076
1     -0.001882
2      0.085299
3     -0.089063
4      0.005383
         ...
437    0.041708
438   -0.005515
439    0.041708
440   -0.045472
441   -0.045472
Name: age, Length: 442, dtype: float64

In [13]:
type(df['age'])

pandas.core.series.Series

In [14]:
df['age'][0]

np.float64(0.038075906433423026)

In [15]:
df['age'][:5]

0    0.038076
1   -0.001882
2    0.085299
3   -0.089063
4    0.005383
Name: age, dtype: float64

In [16]:
df['age'][-5:]

437    0.041708
438   -0.005515
439    0.041708
440   -0.045472
441   -0.045472
Name: age, dtype: float64

In [17]:
df[['age','sex']]

          age       sex
0    0.038076  0.050680
1   -0.001882 -0.044642
2    0.085299  0.050680
3   -0.089063 -0.044642
4    0.005383 -0.044642
..        ...       ...
437  0.041708  0.050680
438 -0.005515  0.050680
439  0.041708  0.050680
440 -0.045472 -0.044642
441 -0.045472 -0.044642

[442 rows x 2 columns]

* ```.loc```  indices value
* ```.iloc``` integer value

In [18]:
df.iloc[0] #df[0] not works

age    0.038076
sex    0.050680
bmi    0.061696
bp     0.021872
s1    -0.044223
s2    -0.034821
s3    -0.043401
s4    -0.002592
s5     0.019907
s6    -0.017646
Name: 0, dtype: float64

In [19]:
df.loc[0]

age    0.038076
sex    0.050680
bmi    0.061696
bp     0.021872
s1    -0.044223
s2    -0.034821
s3    -0.043401
s4    -0.002592
s5     0.019907
s6    -0.017646
Name: 0, dtype: float64

In [20]:
df.loc[4,'age'] #but not df.iloc[4,'age']

np.float64(0.005383060374248237)

In [21]:
df.iloc[4,0:2]

age    0.005383
sex   -0.044642
Name: 4, dtype: float64

In [22]:
df.loc[4,['age','sex']]

age    0.005383
sex   -0.044642
Name: 4, dtype: float64

In [23]:
df.loc[df.age<0.005383]

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
5,-0.092695,-0.044642,-0.040696,-0.019442,-0.068991,-0.079288,0.041277,-0.076395,-0.041176,-0.096346
6,-0.045472,0.050680,-0.047163,-0.015999,-0.040096,-0.024800,0.000779,-0.039493,-0.062917,-0.038357
9,-0.070900,-0.044642,0.039062,-0.033213,-0.012577,-0.034508,-0.024993,-0.002592,0.067737,-0.013504
...,...,...,...,...,...,...,...,...,...,...
435,-0.012780,-0.044642,-0.023451,-0.040099,-0.016704,0.004636,-0.017629,-0.002592,-0.038460,-0.038357
436,-0.056370,-0.044642,-0.074108,-0.050427,-0.024960,-0.047034,0.092820,-0.076395,-0.061176,-0.046641
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064

In [24]:
import numpy as np

In [25]:
df=pd.DataFrame(np.random.rand(9,4),index=list('abcdefghi'),columns=list("ABCD"))

In [26]:
df.shape

(9, 4)

In [27]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, a to i
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       9 non-null      float64
 1   B       9 non-null      float64
 2   C       9 non-null      float64
 3   D       9 non-null      float64
dtypes: float64(4)
memory usage: 360.0+ bytes

In [29]:
df.head()

          A         B         C         D
a  0.243368  0.818506  0.080704  0.662306
b  0.035708  0.581212  0.870089  0.938093
c  0.444515  0.940801  0.721651  0.325125
d  0.088175  0.893682  0.889545  0.670209
e  0.039985  0.191326  0.359122  0.672229

In [30]:
another_df=pd.DataFrame(
    np.random.rand(100,4),
    index=range(10,110),
    columns=list("ABCD")
)

In [31]:
another_df.head()

           A         B         C         D
10  0.682887  0.425055  0.178445  0.821604
11  0.573542  0.634122  0.176388  0.803118
12  0.829877  0.069572  0.981621  0.143255
13  0.337744  0.769323  0.430194  0.614661
14  0.415918  0.747617  0.716886  0.813917

In [32]:
df.loc['a']

A    0.243368
B    0.818506
C    0.080704
D    0.662306
Name: a, dtype: float64

In [33]:
df.iloc[0:4,0:3]

          A         B         C
a  0.243368  0.818506  0.080704
b  0.035708  0.581212  0.870089
c  0.444515  0.940801  0.721651
d  0.088175  0.893682  0.889545

In [34]:
selector=lambda df: df['A']>0.5

In [35]:
selector

In [36]:
df.loc[selector]

          A         B         C         D
f  0.944186  0.442826  0.922828  0.053808
g  0.504912  0.562916  0.509334  0.072154
i  0.572787  0.093344  0.622962  0.181164

In [37]:
selector =lambda df:(df['A']>0.5) &(df['B']<0.2)

In [38]:
df.loc[selector]

          A         B         C         D
i  0.572787  0.093344  0.622962  0.181164

## Adding a column in the dataframe

In [39]:
df['E']=df['A']*100

In [40]:
df

          A         B         C         D          E
a  0.243368  0.818506  0.080704  0.662306  24.336797
b  0.035708  0.581212  0.870089  0.938093   3.570773
c  0.444515  0.940801  0.721651  0.325125  44.451509
d  0.088175  0.893682  0.889545  0.670209   8.817535
e  0.039985  0.191326  0.359122  0.672229   3.998526
f  0.944186  0.442826  0.922828  0.053808  94.418641
g  0.504912  0.562916  0.509334  0.072154  50.491187
h  0.482069  0.530967  0.363899  0.683341  48.206895
i  0.572787  0.093344  0.622962  0.181164  57.278730

In [41]:
criteria=df['A']<0.2

In [44]:
criteria

a    False
b     True
c    False
d     True
e     True
f    False
g    False
h    False
i    False
Name: A, dtype: bool

In [43]:
df.loc[criteria,'A']=0
df

          A         B         C         D          E
a  0.243368  0.818506  0.080704  0.662306  24.336797
b  0.000000  0.581212  0.870089  0.938093   3.570773
c  0.444515  0.940801  0.721651  0.325125  44.451509
d  0.000000  0.893682  0.889545  0.670209   8.817535
e  0.000000  0.191326  0.359122  0.672229   3.998526
f  0.944186  0.442826  0.922828  0.053808  94.418641
g  0.504912  0.562916  0.509334  0.072154  50.491187
h  0.482069  0.530967  0.363899  0.683341  48.206895
i  0.572787  0.093344  0.622962  0.181164  57.278730

In [45]:
cities=["mumbai",'kolkata','delhi','chennia','bengalure','pune','hyderabad','indore','varanasi']

In [46]:
df['city']=cities

In [47]:
df

          A         B         C         D          E       city
a  0.243368  0.818506  0.080704  0.662306  24.336797     mumbai
b  0.000000  0.581212  0.870089  0.938093   3.570773    kolkata
c  0.444515  0.940801  0.721651  0.325125  44.451509      delhi
d  0.000000  0.893682  0.889545  0.670209   8.817535    chennia
e  0.000000  0.191326  0.359122  0.672229   3.998526  bengalure
f  0.944186  0.442826  0.922828  0.053808  94.418641       pune
g  0.504912  0.562916  0.509334  0.072154  50.491187  hyderabad
h  0.482069  0.530967  0.363899  0.683341  48.206895     indore
i  0.572787  0.093344  0.622962  0.181164  57.278730   varanasi

In [48]:
df_copy=df.copy()

In [59]:
criteria=df_copy['city'].isin(['pune','delhii'])

In [54]:
criteria

a    False
b    False
c     True
d    False
e    False
f     True
g    False
h    False
i    False
Name: city, dtype: bool

In [53]:
df_copy.loc[df.city=='delhi','city']='delhii'

In [57]:
df_copy

          A         B         C         D          E       city
a  0.243368  0.818506  0.080704  0.662306  24.336797     mumbai
b  0.000000  0.581212  0.870089  0.938093   3.570773    kolkata
c  0.444515  0.940801  0.721651  0.325125  44.451509     delhii
d  0.000000  0.893682  0.889545  0.670209   8.817535    chennia
e  0.000000  0.191326  0.359122  0.672229   3.998526  bengalure
f  0.944186  0.442826  0.922828  0.053808  94.418641       pune
g  0.504912  0.562916  0.509334  0.072154  50.491187  hyderabad
h  0.482069  0.530967  0.363899  0.683341  48.206895     indore
i  0.572787  0.093344  0.622962  0.181164  57.278730   varanasi

In [60]:
df_copy[criteria]

          A         B         C         D          E    city
c  0.444515  0.940801  0.721651  0.325125  44.451509  delhii
f  0.944186  0.442826  0.922828  0.053808  94.418641    pune

In [80]:
df_copy.loc[df_copy.city=='delho',['city','new_cities']]='delhi'

In [81]:
df_copy

          A         B         C         D          E       city new_cities
a  0.243368  0.818506  0.080704  0.662306  24.336797     mumbai        NaN
b  0.000000  0.581212  0.870089  0.938093   3.570773    kolkata        NaN
c  0.444515  0.940801  0.721651  0.325125  44.451509      delhi      delhi
d  0.000000  0.893682  0.889545  0.670209   8.817535    chennia        NaN
e  0.000000  0.191326  0.359122  0.672229   3.998526  bengalure        NaN
f  0.944186  0.442826  0.922828  0.053808  94.418641       pune        NaN
g  0.504912  0.562916  0.509334  0.072154  50.491187  hyderabad        NaN
h  0.482069  0.530967  0.363899  0.683341  48.206895     indore        NaN
i  0.572787  0.093344  0.622962  0.181164  57.278730   varanasi        NaN

In [82]:
df_copy.drop(['new_cities'],axis=1)

          A         B         C         D          E       city
a  0.243368  0.818506  0.080704  0.662306  24.336797     mumbai
b  0.000000  0.581212  0.870089  0.938093   3.570773    kolkata
c  0.444515  0.940801  0.721651  0.325125  44.451509      delhi
d  0.000000  0.893682  0.889545  0.670209   8.817535    chennia
e  0.000000  0.191326  0.359122  0.672229   3.998526  bengalure
f  0.944186  0.442826  0.922828  0.053808  94.418641       pune
g  0.504912  0.562916  0.509334  0.072154  50.491187  hyderabad
h  0.482069  0.530967  0.363899  0.683341  48.206895     indore
i  0.572787  0.093344  0.622962  0.181164  57.278730   varanasi

In [84]:
df_copy.sample(3)

          A         B         C         D          E       city new_cities
f  0.944186  0.442826  0.922828  0.053808  94.418641       pune        NaN
g  0.504912  0.562916  0.509334  0.072154  50.491187  hyderabad        NaN
h  0.482069  0.530967  0.363899  0.683341  48.206895     indore        NaN

In [86]:
df_copy.sample(3,random_state=42)

          A         B         C         D          E     city new_cities
h  0.482069  0.530967  0.363899  0.683341  48.206895   indore        NaN
b  0.000000  0.581212  0.870089  0.938093   3.570773  kolkata        NaN
f  0.944186  0.442826  0.922828  0.053808  94.418641     pune        NaN

In [90]:
df_copy.sample(3,replace=True)

          A         B         C         D          E       city new_cities
c  0.444515  0.940801  0.721651  0.325125  44.451509      delhi      delhi
g  0.504912  0.562916  0.509334  0.072154  50.491187  hyderabad        NaN
g  0.504912  0.562916  0.509334  0.072154  50.491187  hyderabad        NaN